// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactApp1.Server.Data;

#nullable disable

namespace ReactApp1.Server.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20250319213034_OkThisIsFrTheLastOne")]
    partial class OkThisIsFrTheLastOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReactApp1.Server.Entities.Film", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AlapAr")
                        .HasColumnType("INT(11)");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EredetiCim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EredetiNyelv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gyarto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMDB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Jatekido")
                        .HasColumnType("INT(4)");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Korhatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendezo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Szereplok")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Szinkron")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Foglalas.FoglalasAdatok", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("FoglalasIdopontja")
                        .HasColumnType("DateTime");

                    b.Property<int>("UserID")
                        .HasColumnType("int(11)");

                    b.HasKey("id");

                    b.HasIndex("UserID");

                    b.ToTable("FoglalasAdatok");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Foglalas.FoglaltSzekek", b =>
                {
                    b.Property<int>("Teremid")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Vetitesid")
                        .HasColumnType("int");

                    b.Property<int>("FoglalasAdatokid")
                        .HasColumnType("int");

                    b.HasKey("Teremid", "X", "Y", "Vetitesid");

                    b.HasIndex("FoglalasAdatokid");

                    b.ToTable("FoglaltSzekek");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Terem.Szekek", b =>
                {
                    b.Property<int>("Teremid")
                        .HasColumnType("int(5)");

                    b.Property<int>("X")
                        .HasColumnType("int(2)");

                    b.Property<int>("Y")
                        .HasColumnType("int(2)");

                    b.Property<int>("Allapot")
                        .HasColumnType("int(1)");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Teremid", "X", "Y");

                    b.ToTable("Szekek");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Terem.Terem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(5)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Terem");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("userID"));

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("accountStatus")
                        .HasMaxLength(1)
                        .HasColumnType("int(1)");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("char(84)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("refreshTokenExpiry")
                        .HasColumnType("DateTime");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(30)");

                    b.HasKey("userID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Vetites.Vetites", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(5)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Filmid")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("DateTime");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Teremid")
                        .HasColumnType("int(5)");

                    b.HasKey("id");

                    b.HasIndex("Filmid");

                    b.HasIndex("Teremid");

                    b.ToTable("Vetites");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Vetites.VetitesSzekek", b =>
                {
                    b.Property<int>("Teremid")
                        .HasColumnType("int(5)");

                    b.Property<int>("X")
                        .HasColumnType("int(2)");

                    b.Property<int>("Y")
                        .HasColumnType("int(2)");

                    b.Property<int>("Vetitesid")
                        .HasColumnType("int(5)");

                    b.Property<int>("FoglalasAllapot")
                        .HasColumnType("int");

                    b.HasKey("Teremid", "X", "Y", "Vetitesid");

                    b.HasIndex("Vetitesid");

                    b.ToTable("VetitesSzekek");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Foglalas.FoglalasAdatok", b =>
                {
                    b.HasOne("ReactApp1.Server.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Foglalas.FoglaltSzekek", b =>
                {
                    b.HasOne("ReactApp1.Server.Entities.Foglalas.FoglalasAdatok", "FoglalasAdatok")
                        .WithMany()
                        .HasForeignKey("FoglalasAdatokid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoglalasAdatok");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Terem.Szekek", b =>
                {
                    b.HasOne("ReactApp1.Server.Entities.Terem.Terem", "Terem")
                        .WithMany("Szekek")
                        .HasForeignKey("Teremid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terem");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Vetites.Vetites", b =>
                {
                    b.HasOne("ReactApp1.Server.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("Filmid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApp1.Server.Entities.Terem.Terem", "Terem")
                        .WithMany()
                        .HasForeignKey("Teremid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Terem");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Vetites.VetitesSzekek", b =>
                {
                    b.HasOne("ReactApp1.Server.Entities.Vetites.Vetites", "Vetites")
                        .WithMany()
                        .HasForeignKey("Vetitesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApp1.Server.Entities.Terem.Szekek", "Szekek")
                        .WithMany()
                        .HasForeignKey("Teremid", "X", "Y")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApp1.Server.Entities.Foglalas.FoglaltSzekek", "FoglaltSzekek")
                        .WithOne("VetitesSzekek")
                        .HasForeignKey("ReactApp1.Server.Entities.Vetites.VetitesSzekek", "Teremid", "X", "Y", "Vetitesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoglaltSzekek");

                    b.Navigation("Szekek");

                    b.Navigation("Vetites");
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Foglalas.FoglaltSzekek", b =>
                {
                    b.Navigation("VetitesSzekek")
                        .IsRequired();
                });

            modelBuilder.Entity("ReactApp1.Server.Entities.Terem.Terem", b =>
                {
                    b.Navigation("Szekek");
                });
#pragma warning restore 612, 618
        }
    }
}
