name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_VERSION: '6.0.x'
      APP_TOKEN: ${{ secrets.JWT_TOKEN }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      MYSQL_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      env:
        APP_TOKEN: ${{ secrets.JWT_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        MYSQL_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output publish
      env:
        APP_TOKEN: ${{ secrets.JWT_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        MYSQL_CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}