name: Build and Deploy (Development)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_VERSION: '8.0.x'
      ASPNETCORE_ENVIRONMENT: "Development"  
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Debug --no-restore 
      env:
        JWT_TOKEN: ${{ secrets.JWT_TOKEN }} 
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    
    - name: Publish Development Build
      run: dotnet publish --configuration Debug --no-build --output publish-dev
      env:
        JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    
    - name: Deploy with Development Secrets
      run: |
        cat <<EOF > .env
        ASPNETCORE_ENVIRONMENT=Development
        JWT_TOKEN=${{ secrets.JWT_TOKEN }}
        SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
        CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}
        EOF
        
        dotnet publish-dev/ReactApp1.Server.dll --urls "http://0.0.0.0:5082;https://0.0.0.0:7153" &
        sleep 15
        
        curl -k https://localhost:7153/env-check
      working-directory: ./